server:
  port: 8090
  servlet:
    context-path: /omega-buy
logging:
  level:
    root: info
#  org.springframework.data: debug
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:${DATABASE_URL:}
    hikari:
      connectionTimeout: 30000
      idleTimeout: 100000
      maxLifetime: 900000
      maximum-pool-size: 20
      minimum-idle: 10
    initialization-mode: never
  messages:
    basename: static/i18n/message
    encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        default_schema: omega_buy
    show-sql: true
    open-in-view: false
  banner:
    location: classpath:banner.txt
  main:
    banner-mode: log
custom:
  auth-service: ${AUTH_SERVICE:}
  client-id: ${CLIENT_ID:}
  client-secret: ${CLIENT_SECRET:}